import { Component } from '@angular/core';
import { ProjectCardComponent, Project } from '../../components/project-card/project-card.component';
import { RevealDirective } from '../../shared/reveal.directive';

@Component({
  selector: 'app-projects',
  standalone: true,
  imports: [ProjectCardComponent, RevealDirective],
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.scss']
})
export class ProjectsComponent {
  readonly projects: Project[] = [
    {
      title: 'Drinko',
      subtitle: 'Native iOS · in active development',
      description:
        'A social drink tracker for iOS. Drinko offers a real-time blood alcohol estimator along with a drink tracker to monitor your night out. Additionally group planning, running tallies, and a game tournament bracket engine are available for friends to interact with eachother.',
      status: 'In development',
      featured: true,
      year: '2026',
      tags: ['Swift', 'SwiftData', 'HealthKit', 'StoreKit', 'iOS'],
      highlights: [
        'Real-time BAC estimation using the Widmark formula, calculated by HealthKit biometrics and a live drink log.',
        'Tournament bracket engine for group games. Seeding, progression, and results persisted with SwiftData.',
        'Offline-first local persistence layer so the app stays accurate without a network connection.',
        'Subscription tier built on StoreKit, with an entitlement model gating premium tracking features.'
      ],
      // FUTURE SCREENSHOTS
      screenshots: [
        'assets/projectscreenshots/Drinko1.jpg',
        'assets/projectscreenshots/Drinko2.jpg',
        'assets/projectscreenshots/Drinko3.jpg',
        'assets/projectscreenshots/Drinko4.jpg',
        'assets/projectscreenshots/Drinko5.jpg',
        'assets/projectscreenshots/Drinko6.jpg'
      ]
    },
    {
      title: 'B2B Pipeline Analytics',
      subtitle: 'Revenue analytics case study',
      description:
        'A revenue-analytics case built on a synthetic B2B SaaS CRM: funnel conversion, an open-pipeline quality score, closed-lost analysis, and an ideal customer profile, modeled in BigQuery and reported in Looker Studio. All data is synthetic and generated by a seeded, documented Python script.',
      github: 'Coming Soon'
      year: '2026',
      tags: [ 'RevOps', 'SQL', 'Python', 'Looker Studio'],
      highlights: [
        '30,000 leads traced to 4,689 SQLs and 1,360 wins ($42.5M ACV), with stage conversion broken out by channel, segment, and rep cohort.',
        'Weighted pipeline score (fit, engagement, velocity, age) backtested against outcomes: A-tier 46% win rate vs. 26% for B and 8% for C.',
        'ICP identified by expected revenue per SQL per month of sales cycle, pointing to Mid-Market Software, Financial Services, and Healthcare.',
        'One-command BigQuery load from schema to views, plus a Looker Studio build spec with a reconciliation checklist.'
      ]
    },
    {
      title: 'Commission Calculator',
      subtitle: 'Rule-driven incentive compensation engine',
      description:
        'A single-file commission calculator with a full audit trail. Upload deal-level data, define rules that route each deal to its own rate table, and get a payout where every step is traceable back to the formula and inputs that produced it.',
      github: 'https://github.com/raneill26/CommissionCalculator',
      year: '2026',
      tags: ['JavaScript', 'HTML/CSS', 'Node', 'Netlify', 'Incentive Comp'],
      highlights: [
        'Calculation engine that emits an audit step for every number, so a plan can be verified without touching the UI.',
        'Customizable per-deal and period-cumulative rate tables',
        'Link to site: https://raneill26.github.io/CommissionCalculator/'
      ],
      screenshots: [
        'assets/projectscreenshots/CommissionCalculator.png',
        'assets/projectscreenshots/CommissionCalculator2.png'
      ]
    },
    {
      title: 'AInterviewer',
      subtitle: 'Full-stack web platform',
      description:
        'An AI-assisted technical interview trainer built with a team and integrated into the UNC Computer Science department site. Students work real interview problems and get scaffolded hints and feedback instead of an answer key.',
      github: 'https://github.com/raneill26/AInterview',
      year: '2025',
      tags: ['Angular', 'FastAPI', 'TypeScript', 'SQL', 'Team Project'],
      highlights: [
        'Student workspace for selecting, attempting, and submitting interview questions.',
        'AI feedback layer that returns progressive hints rather than solutions.',
        'Admin console for creating, editing, and curating the question bank.'
      ],
      screenshots: [
        'assets/projectscreenshots/AI1studentmainview.png',
        'assets/projectscreenshots/AI2selectedquestion.png',
        'assets/projectscreenshots/AI3answered.png',
        'assets/projectscreenshots/AI4asked.png',
        'assets/projectscreenshots/AI5adminview.png',
        'assets/projectscreenshots/AI6create.png',
        'assets/projectscreenshots/AI7edit.png'
      ]
    },
    {
      title: 'Flappy Bird in MIPS Assembly',
      subtitle: 'Hardware + bare-metal game',
      description:
        'Flappy Bird written in MIPS assembly and run on a Nexys A7 FPGA board. Executing on a single-cycle MIPS processor I built from scratch in SystemVerilog.',
      github: 'https://github.com/raneill26/FlappyBird',
      year: '2025',
      tags: ['MIPS', 'SystemVerilog', 'FPGA', 'Game Dev'],
      highlights: [
        'Custom single cycle MIPS processor implemented in SystemVerilog.',
        'Game loop, collision, and VGA rendering written directly in assembly.'
      ],
      screenshots: [
        'assets/projectscreenshots/Bird1.png',
        'assets/projectscreenshots/Bird2.png'
      ]
    },
    {
      title: 'Akari',
      subtitle: 'JavaFX puzzle game',
      description:
        'A complete JavaFX implementation of Akari (Light Up), including the puzzle model, constraint validation, and an interactive board with live solution checking.',
      github: 'https://github.com/raneill26/Akari',
      year: '2024',
      tags: ['Java', 'JavaFX', 'Game Dev'],
      screenshots: [
        'assets/projectscreenshots/Akari2.png',
        'assets/projectscreenshots/Akari3.png'
      ]
    },
    {
      title: 'Ethics of AI',
      subtitle: 'Research study',
      description:
        'A two-part study analyzing bias in generative AI systems — how it surfaces in model output, and what that means for the people deploying these tools.',
      github: 'https://github.com/raneill26/Ethics-of-AI',
      year: '2024',
      tags: ['Research', 'AI Ethics', 'Team Project']
    }
  ];
}
